[build]
  # Directory with the serverless Lambda functions to deploy to AWS.
  functions = "functions"

[[redirects]]
  from = "/api"
  to = "http://81.25.125.14:3000/"
  status = 200
  force = true # COMMENT: ensure that we always redirect
  headers = {X-From = "Netlify"}

[[redirects]]
  from = "/api/upload"
  to = "http://81.25.125.14:3000/upload"
  status = 200
  force = true # COMMENT: ensure that we always redirect
  headers = {X-From = "Netlify"}

[[redirects]]
  from = "/api/submit"
  to = "http://81.25.125.14:3000/"
  status = 200
  force = true # COMMENT: ensure that we always redirect
  headers = {X-From = "Netlify"}